//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.17 at 11:06:24 AM IST 
//


package com.codenotfound.types.flightsearch;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for flightInfoVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="flightInfoVO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="productDateTime" type="{http://codenotfound.com/types/flightsearch}productDateTimeVO" minOccurs="0"/&gt;
 *         &lt;element name="location" type="{http://codenotfound.com/types/flightsearch}locationVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="companyId" type="{http://codenotfound.com/types/flightsearch}companyVO" minOccurs="0"/&gt;
 *         &lt;element name="flightOrtrainNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flightInfoVO", propOrder = {
    "productDateTime",
    "location",
    "companyId",
    "flightOrtrainNumber"
})
public class FlightInfoVO {

    protected ProductDateTimeVO productDateTime;
    protected List<LocationVO> location;
    protected CompanyVO companyId;
    protected String flightOrtrainNumber;

    /**
     * Gets the value of the productDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link ProductDateTimeVO }
     *     
     */
    public ProductDateTimeVO getProductDateTime() {
        return productDateTime;
    }

    /**
     * Sets the value of the productDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductDateTimeVO }
     *     
     */
    public void setProductDateTime(ProductDateTimeVO value) {
        this.productDateTime = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the location property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LocationVO }
     * 
     * 
     */
    public List<LocationVO> getLocation() {
        if (location == null) {
            location = new ArrayList<LocationVO>();
        }
        return this.location;
    }

    /**
     * Gets the value of the companyId property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyVO }
     *     
     */
    public CompanyVO getCompanyId() {
        return companyId;
    }

    /**
     * Sets the value of the companyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyVO }
     *     
     */
    public void setCompanyId(CompanyVO value) {
        this.companyId = value;
    }

    /**
     * Gets the value of the flightOrtrainNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightOrtrainNumber() {
        return flightOrtrainNumber;
    }

    /**
     * Sets the value of the flightOrtrainNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightOrtrainNumber(String value) {
        this.flightOrtrainNumber = value;
    }

	public void setLocation(List<LocationVO> location) {
		this.location = location;
	}

}
