//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.17 at 11:06:24 AM IST 
//


package com.codenotfound.types.flightsearch;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fareDetailsVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fareDetailsVO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="segmentRef" type="{http://codenotfound.com/types/flightsearch}SegmentRefVO" minOccurs="0"/&gt;
 *         &lt;element name="groupOfFares" type="{http://codenotfound.com/types/flightsearch}GrpOfFaresVO" minOccurs="0"/&gt;
 *         &lt;element name="majCabin" type="{http://codenotfound.com/types/flightsearch}MajCabinVO" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fareDetailsVO", propOrder = {
    "segmentRef",
    "groupOfFares",
    "majCabin"
})
public class FareDetailsVO {

    protected SegmentRefVO segmentRef;
    protected GrpOfFaresVO groupOfFares;
    protected MajCabinVO majCabin;

    /**
     * Gets the value of the segmentRef property.
     * 
     * @return
     *     possible object is
     *     {@link SegmentRefVO }
     *     
     */
    public SegmentRefVO getSegmentRef() {
        return segmentRef;
    }

    /**
     * Sets the value of the segmentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SegmentRefVO }
     *     
     */
    public void setSegmentRef(SegmentRefVO value) {
        this.segmentRef = value;
    }

    /**
     * Gets the value of the groupOfFares property.
     * 
     * @return
     *     possible object is
     *     {@link GrpOfFaresVO }
     *     
     */
    public GrpOfFaresVO getGroupOfFares() {
        return groupOfFares;
    }

    /**
     * Sets the value of the groupOfFares property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrpOfFaresVO }
     *     
     */
    public void setGroupOfFares(GrpOfFaresVO value) {
        this.groupOfFares = value;
    }

    /**
     * Gets the value of the majCabin property.
     * 
     * @return
     *     possible object is
     *     {@link MajCabinVO }
     *     
     */
    public MajCabinVO getMajCabin() {
        return majCabin;
    }

    /**
     * Sets the value of the majCabin property.
     * 
     * @param value
     *     allowed object is
     *     {@link MajCabinVO }
     *     
     */
    public void setMajCabin(MajCabinVO value) {
        this.majCabin = value;
    }

}
