//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.17 at 11:06:24 AM IST 
//


package com.codenotfound.types.flightsearch;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for flightIndexVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="flightIndexVO"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="requestedSegmentRef" type="{http://codenotfound.com/types/flightsearch}reqSegmentRefVO" minOccurs="0"/&gt;
 *         &lt;element name="groupOfFlights" type="{http://codenotfound.com/types/flightsearch}groupOfFlightsVO" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flightIndexVO", propOrder = {
    "requestedSegmentRef",
    "groupOfFlights"
})
public class FlightIndexVO {

    protected ReqSegmentRefVO requestedSegmentRef;
    protected List<GroupOfFlightsVO> groupOfFlights;

    /**
     * Gets the value of the requestedSegmentRef property.
     * 
     * @return
     *     possible object is
     *     {@link ReqSegmentRefVO }
     *     
     */
    public ReqSegmentRefVO getRequestedSegmentRef() {
        return requestedSegmentRef;
    }

    /**
     * Sets the value of the requestedSegmentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReqSegmentRefVO }
     *     
     */
    public void setRequestedSegmentRef(ReqSegmentRefVO value) {
        this.requestedSegmentRef = value;
    }

    /**
     * Gets the value of the groupOfFlights property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupOfFlights property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupOfFlights().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroupOfFlightsVO }
     * 
     * 
     */
    public List<GroupOfFlightsVO> getGroupOfFlights() {
        if (groupOfFlights == null) {
            groupOfFlights = new ArrayList<GroupOfFlightsVO>();
        }
        return this.groupOfFlights;
    }

	public void setGroupOfFlights(List<GroupOfFlightsVO> groupOfFlights) {
		this.groupOfFlights = groupOfFlights;
	}

}
