//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.17 at 11:06:24 AM IST 
//


package com.codenotfound.types.flightsearch;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.codenotfound.types.flightsearch package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.codenotfound.types.flightsearch
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Flight }
     * 
     */
    public Flight createFlight() {
        return new Flight();
    }

    /**
     * Create an instance of {@link FareMasterPriceResponseVO }
     * 
     */
    public FareMasterPriceResponseVO createFareMasterPriceResponseVO() {
        return new FareMasterPriceResponseVO();
    }

    /**
     * Create an instance of {@link FlightIndexVO }
     * 
     */
    public FlightIndexVO createFlightIndexVO() {
        return new FlightIndexVO();
    }

    /**
     * Create an instance of {@link RecommendationVO }
     * 
     */
    public RecommendationVO createRecommendationVO() {
        return new RecommendationVO();
    }

    /**
     * Create an instance of {@link ReqSegmentRefVO }
     * 
     */
    public ReqSegmentRefVO createReqSegmentRefVO() {
        return new ReqSegmentRefVO();
    }

    /**
     * Create an instance of {@link GroupOfFlightsVO }
     * 
     */
    public GroupOfFlightsVO createGroupOfFlightsVO() {
        return new GroupOfFlightsVO();
    }

    /**
     * Create an instance of {@link FlightDetailsVO }
     * 
     */
    public FlightDetailsVO createFlightDetailsVO() {
        return new FlightDetailsVO();
    }

    /**
     * Create an instance of {@link FlightInfoVO }
     * 
     */
    public FlightInfoVO createFlightInfoVO() {
        return new FlightInfoVO();
    }

    /**
     * Create an instance of {@link ProductDateTimeVO }
     * 
     */
    public ProductDateTimeVO createProductDateTimeVO() {
        return new ProductDateTimeVO();
    }

    /**
     * Create an instance of {@link LocationVO }
     * 
     */
    public LocationVO createLocationVO() {
        return new LocationVO();
    }

    /**
     * Create an instance of {@link CompanyVO }
     * 
     */
    public CompanyVO createCompanyVO() {
        return new CompanyVO();
    }

    /**
     * Create an instance of {@link ItemNumberVO }
     * 
     */
    public ItemNumberVO createItemNumberVO() {
        return new ItemNumberVO();
    }

    /**
     * Create an instance of {@link ItemNumIdVO }
     * 
     */
    public ItemNumIdVO createItemNumIdVO() {
        return new ItemNumIdVO();
    }

    /**
     * Create an instance of {@link RecPriceInfoVO }
     * 
     */
    public RecPriceInfoVO createRecPriceInfoVO() {
        return new RecPriceInfoVO();
    }

    /**
     * Create an instance of {@link MonetaryDetailVO }
     * 
     */
    public MonetaryDetailVO createMonetaryDetailVO() {
        return new MonetaryDetailVO();
    }

    /**
     * Create an instance of {@link SegFlightRefVO }
     * 
     */
    public SegFlightRefVO createSegFlightRefVO() {
        return new SegFlightRefVO();
    }

    /**
     * Create an instance of {@link RefDetailVO }
     * 
     */
    public RefDetailVO createRefDetailVO() {
        return new RefDetailVO();
    }

    /**
     * Create an instance of {@link PaxFareProduct }
     * 
     */
    public PaxFareProduct createPaxFareProduct() {
        return new PaxFareProduct();
    }

    /**
     * Create an instance of {@link PaxFareDetailVO }
     * 
     */
    public PaxFareDetailVO createPaxFareDetailVO() {
        return new PaxFareDetailVO();
    }

    /**
     * Create an instance of {@link PaxReferVO }
     * 
     */
    public PaxReferVO createPaxReferVO() {
        return new PaxReferVO();
    }

    /**
     * Create an instance of {@link CodeShareDetailsVO }
     * 
     */
    public CodeShareDetailsVO createCodeShareDetailsVO() {
        return new CodeShareDetailsVO();
    }

    /**
     * Create an instance of {@link PricingTktVO }
     * 
     */
    public PricingTktVO createPricingTktVO() {
        return new PricingTktVO();
    }

    /**
     * Create an instance of {@link TravellerVO }
     * 
     */
    public TravellerVO createTravellerVO() {
        return new TravellerVO();
    }

    /**
     * Create an instance of {@link PaxTaxDetailsVO }
     * 
     */
    public PaxTaxDetailsVO createPaxTaxDetailsVO() {
        return new PaxTaxDetailsVO();
    }

    /**
     * Create an instance of {@link TaxDetailsVO }
     * 
     */
    public TaxDetailsVO createTaxDetailsVO() {
        return new TaxDetailsVO();
    }

    /**
     * Create an instance of {@link FareVO }
     * 
     */
    public FareVO createFareVO() {
        return new FareVO();
    }

    /**
     * Create an instance of {@link PricingMessageVO }
     * 
     */
    public PricingMessageVO createPricingMessageVO() {
        return new PricingMessageVO();
    }

    /**
     * Create an instance of {@link FreeTxtQualVO }
     * 
     */
    public FreeTxtQualVO createFreeTxtQualVO() {
        return new FreeTxtQualVO();
    }

    /**
     * Create an instance of {@link FareDetailsVO }
     * 
     */
    public FareDetailsVO createFareDetailsVO() {
        return new FareDetailsVO();
    }

    /**
     * Create an instance of {@link SegmentRefVO }
     * 
     */
    public SegmentRefVO createSegmentRefVO() {
        return new SegmentRefVO();
    }

    /**
     * Create an instance of {@link GrpOfFaresVO }
     * 
     */
    public GrpOfFaresVO createGrpOfFaresVO() {
        return new GrpOfFaresVO();
    }

    /**
     * Create an instance of {@link MajCabinVO }
     * 
     */
    public MajCabinVO createMajCabinVO() {
        return new MajCabinVO();
    }

    /**
     * Create an instance of {@link ProductInformationVO }
     * 
     */
    public ProductInformationVO createProductInformationVO() {
        return new ProductInformationVO();
    }

    /**
     * Create an instance of {@link CabinPdtVO }
     * 
     */
    public CabinPdtVO createCabinPdtVO() {
        return new CabinPdtVO();
    }

    /**
     * Create an instance of {@link FarePdtDetailVO }
     * 
     */
    public FarePdtDetailVO createFarePdtDetailVO() {
        return new FarePdtDetailVO();
    }

    /**
     * Create an instance of {@link FareCalcCdeDetailsVO }
     * 
     */
    public FareCalcCdeDetailsVO createFareCalcCdeDetailsVO() {
        return new FareCalcCdeDetailsVO();
    }

    /**
     * Create an instance of {@link BookClsDetailsVO }
     * 
     */
    public BookClsDetailsVO createBookClsDetailsVO() {
        return new BookClsDetailsVO();
    }

}
